{% set version = "0.4.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-vipor
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vipor_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vipor/vipor_{{ version }}.tar.gz
  sha256: baad41e9ddaa13b5a1db1abab34253b27d5b99e5a6a649b2036aaf1483370b9e

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('vipor')"           # [not win]
    - "\"%R%\" -e \"library('vipor')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=vipor
  license: GPL-2.0-or-later
  summary: Generate a violin point plot, a combination of a violin/histogram plot and a scatter plot by offsetting points within a category based on their density using quasirandom noise.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
