travis:
  secure:
    BINSTAR_TOKEN: jgZzdsUgocUanNgNuhBiU4olTX01ZYvW//zun0ogJA5MyzVza/6hPcsn2p5Z8t6N0I4oSxgQKxzgT5O8h++bkpNQexAoOR4uSXxaTp+uvpj8S76lc7uCs9uQUBC0MXP5Xg+9BK/sL1uNCQElZc5yRH+H2IVpSsEl8YQWcRhvQ8/U1LqTYGPl7dp7cP6o5uhGcuaMNNL7nPsMYVEMu14rNxt7JWOQVwnrUrcfvO6W3QWeJgRN1ILfpqHbxVDahhODU+ogZzjHKF8CDoFwUHDg/gEl5x72ukbkM31axTPwvNbc+QcKR37ahX8e+SP5HWfYKccQKi684xy1R0a8teJkVlNOIQRtlZhgurtxcbS+oomBdxzwIe3OTFbqOM13LZSk36CQ32VeQxJffJHtqcDmaKAayRYHqmoCKFrWwMucRlAoIdeuLkratbx303/2vlcFE+Z8M08XDUne2Q8NML/rFtd8teYESHb1PLSuYM/U5bwLCUyKJhSOBzhMJpiuaoJVnvONcpFWLN8FugV+ud4z7227vbRmEtm6/9cE0JXOtCCdZNOVeKFFepZOc9Lo46fK4xa/nbmNH6XyMXlg0C3fXGEjeULZqstnUQrWqmtByBkDUlk8mZdZFxYdKd1gDFxjT9TPBf9QRC94oqhikAhMu6D4RXuLCwdY1m/IlQlnBR4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
