travis:
  secure:
    BINSTAR_TOKEN: tBoNxq9EbmzuSdwYLxYKum9RWLQSmIOJAfuaN4gPHzf4rUZ5RX6/1MUVOcH+BQTVTawu//irHUzT01pklbw3iIWU5EYehBh1/pRgWtnejcJM+Nq2K3QaHCnbMjHzdyexRpLaSrso50qWfK0wLI/vur5sa6aSFafs+48/d3/Bv6dxQ2TOxrAmyNd63HvGkKNLIWOwRrUcQDRgRVfL6GtkyHYHSTF4LiiEx5XlBaQwL9YqTQaWjwKZzm9mfbMwZ5fMaaeKstHKHXZAbMr+IOqpy0GwIy3fOYf2w9cnPnJi1LjdgPYfI+SFGKBAdMgIBDbmyN9g8JP3QqNHCYK1k7vKRtBoYXWAnjsfmmK/EPrIQ4b+9WGODwWqqQIu1c9znmDAi5GzIPPykR34/PHBHhlZfoZfxGWhSbldLbgfZ/4Kytuo3t5ZRmgDfOpDFJCPapO7HVbogpZgLD5ICbP3bHmkz3tJ1I5lz+w5Q4GAxHbJSgKAlCMdqX71qsSdpMvJ/I1M4sXDVqCEX3pWADn+6KViCmmcFZfJeyNUmNq5v+42TK7couR15jruNvZfv+xXdKrbnC6Bt5zKPkfnmJ+w8bjjAi3Ba7JGC4UdEyof1WA+asuWCbJp11Ntfp3rmCjec+GRoQAmqkbQ6F2u4a2GRsyz3lT3yoQPY1PXLa6l5/v2PyQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
