appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: bGY1KYemsaqJUZ4w3uMuzI/92QmUR5ibV7WlGi+86iWhXhdTwB/d8DsGfV8My/J6RRPU+QWdfVew1pXGfX/JagK76ZY4wTI5BLO+dm5z3JQpIApKMt9VKXvNy0lTekASwEp3zNqL2osWDaU5cVy5WLZgOAMIg10X8jBVkIMpe3PBi/K4h/54Zc+01KWPh9Q7rEXhkVGo/wOysgQ6UBRikuppHsrQVYy3/DaclR0gxStvLqyazJj8Dg7G8I4gVEM8tpIo39dFVqGMO/RtnfJwQi3m2UiYw0gTxhZsjXLXL/hvMWS4J0ptlJH8sA0BQdcl07XJnw8iEl7Pxa8anH0Ro5HcOyGxm8eLtt4DrFLRMVc82L0axzERwwgrPXaPNckHqh1LE5vDpbRs9DxLFUYJKhUYR8oGSlP7fJbvdg5T7I1TREXRIaGdhPhjalWbnvRuTchjJN8n+ewuCAokWXeYRv74MselKqxHJmeAIzp8hyuvpJ58GG9dzL4jYiKlWUy0mTgFCGBvFEGFqoCz3WbmqpS3xxA68QdgRi0MgvzraDAQUdMlCv9kMgqfgzjpf+Y4O5pJPhTFu6CYnQ3T2Id5WFTELqcpIVkoS7jqhXw/Srj21ISyc7Umnxpaq/JEg0EXmllUJJGDnkt1AcLa42WMoXSaiQzdtiqg8xRuiD5W8Pk=
conda_forge_output_validation: true
